---
- name: install codecs (arch linux)
  become: yes
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - libmad # mp3 decoder including mp3
  when: ansible_os_family == "Archlinux"

- include_tasks: alsa.yml
