- stat:
    path: "{{ ansible_env.HOME }}/Git/dotfiles"
  register: dotfiles_dir

- name: git clone tkiatd/dotfiles if not exist
  git:
    repo: https://github.com/tkiatd/dotfiles.git
    dest: "{{ ansible_env.HOME }}/Git/dotfiles"
  when: dotfiles_dir.stat.exists == false

    # git remote set-url origin git@github.com:tkiatd/dotfiles.git
    # do this first then if fail use this condition to clone https
- name: make symlinks to dotfiles
  vars:
    dotfiles_location: "{{ ansible_env.HOME }}/Git/dotfiles"
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop:
    - { src: "{{ dotfiles_location }}/.ssh/config", dest: "{{ ansible_env.HOME }}/.ssh/config"}
    - { src: "{{ dotfiles_location }}/.tmux.conf", dest: "{{ ansible_env.HOME }}/.tmux.conf"}
    - { src: "{{ dotfiles_location }}/.vimrc", dest: "{{ ansible_env.HOME }}/.vimrc"}
    - { src: "{{ dotfiles_location }}/.vim/colors", dest: "{{ ansible_env.HOME }}/.vim/colors"}
    - { src: "{{ dotfiles_location }}/.vim/template", dest: "{{ ansible_env.HOME }}/.vim/template"}
    - { src: "{{ dotfiles_location }}/.zshrc", dest: "{{ ansible_env.HOME }}/.zshrc"}
    - { src: "{{ dotfiles_location }}/.zshrc.aliases", dest: "{{ ansible_env.HOME }}/.zshrc.aliases"}
    - { src: "{{ dotfiles_location }}/.zshrc.program", dest: "{{ ansible_env.HOME }}/.zshrc.program"}
  when: dotfiles_location is defined
