- name: fzf -> install
  package:
    name: fzf
    state: latest

- name: fzf -> check if config exists in ~/.zshrc.program
  shell: "cat ~/.zshrc.program | grep '# BEGIN fzf' | wc -l"
  register: config_present
  changed_when: false

- name: fzf -> append config to ~/.zshrc.program if not exist
  blockinfile:
    path: ~/.zshrc.program
    marker: "# {mark}"
    marker_begin: "BEGIN fzf"
    marker_end: "END"
    block: |
      export FZF_DEFAULT_COMMAND="ag --depth 4 --hidden --ignore .git -f -g \"\""
      export FZF_DEFAULT_OPTS="--layout=reverse"
  when: config_present.stdout == "0"
