- name: nodejs -> install nvm
  shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
  args:
    creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"

- name: nodejs -> source nvm then install node from it
  shell: |
    . {{ ansible_env.HOME }}/.nvm/nvm.sh
    nvm install node
    nvm use node
  args:
    creates: "{{ ansible_env.HOME }}/.nvm/versions/node"
