- name: scripts -> check if ~/Git/scripts exist
  stat:
    path: "{{ ansible_env.HOME }}/Git/scripts"
  register: scripts_dir

- name: scripts -> git clone tkiatd/scripts (ssh)
  git:
    repo: git@github.com:tkiatd/scripts.git
    dest: "{{ ansible_env.HOME }}/Git/scripts"
  ignore_errors: yes
  register: git_ssh_clone_result
  when: scripts_dir.stat.exists == false

- name: scripts -> git clone tkiatd/scripts (http, fallback)
  git:
    repo: https://github.com/tkiatd/scripts.git
    dest: "{{ ansible_env.HOME }}/Git/scripts"
  when: scripts_dir.stat.exists == false and git_ssh_clone_result.failed == true

- block: # write config to .zshenv
  - name: scripts -> define config marker
    set_fact:
      marker_scripts: "Scripts ================================"

  - name: scripts -> check if config exists in ~/.zshenv
    shell: "cat ~/.zshenv | grep '{{ marker_scripts }}' | wc -l"
    register: scripts_config
    changed_when: false

  - name: scripts -> ensure config exists in ~/.zshenv
    blockinfile:
      path: ~/.zshenv
      marker: "# {mark}"
      marker_begin: "{{ marker_scripts }}"
      marker_end: "{{ marker_section_end }}"
      block: |
        local git_dir=~/Git
        if [ -d $git_dir/scripts/ ]; then
          for dir in $git_dir/scripts/*; do
            if [[ $(basename $dir) == bash || $(basename $dir) == python ]]; then
              export PATH=$PATH:$dir
            fi
          done
        fi
    when: scripts_config.stdout == "0"
