- name: vim -> install
  package:
    name: vim
    state: latest

- name: vim directories -> create backup, swap, undo folders inside ~/.vim
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - ~/.vim/backup
    - ~/.vim/undo
    - ~/.vim/swap

- name: vim directories -> define config marker
  set_fact:
    marker_vim_directories: "config: directories"

- name: vim directories -> check if config exists in ~/.vimrc
  shell: "cat ~/.vimrc | grep '{{ marker_vim_directories }}' | wc -l"
  register: vim_directories_config
  changed_when: false

- name: vim directories -> ensure config exists in ~/.vimrc
  blockinfile:
    path: ~/.vimrc
    marker: "\" {mark}"
    marker_begin: "BEGIN {{ marker_vim_directories }}"
    marker_end: "END"
    block: |
      set backupdir=~/.vim/backup//
      set directory=~/.vim/swap//
      set undodir=~/.vim/undo//
  when: vim_directories_config.stdout == "0"

# - name: source ~/.vimrc
#   shell: vim -c "source ~/.vimrc" -c qa
#   changed_when: false
