- block:
  - name: vim-pathogen -> create folders if not exist
    file:
      path: "{{ item }}"
      state: directory
    loop:
      - ~/.vim/bundle
      - ~/.vim/autoload
  - name: vim-pathogen -> download source
    get_url:
      url: https://tpo.pe/pathogen.vim
      dest: ~/.vim/autoload/pathogen.vim

- block:
  - name: coc.nvim -> ensure folder exists for upcoming archive
    file:
      path: ~/.vim/pack/coc/start
      state: directory
  - name: coc.nvim -> check if archive file exist
    stat:
      path: ~/.vim/pack/coc/start/coc-nvim-archive
    register: coc_nvim_archive
  - block:
    - name: coc.nvim -> download archive to this folder
      get_url:
        url: https://github.com/neoclide/coc.nvim/archive/release.tar.gz
        dest: ~/.vim/pack/coc/start/coc-nvim-archive
    - name: coc.nvim -> extract archive
      unarchive:
        src: ~/.vim/pack/coc/start/coc-nvim-archive
        dest: ~/.vim/pack/coc/start/
    when: coc_nvim_archive.stat.exists == false
  - name: coc.nvim -> check if package.json exist
    stat:
      path: ~/.config/coc/extensions/package.json
    register: package_json
  - name: coc.nvim -> create package.json if not exist
    copy:
      dest: ~/.config/coc/extensions/package.json
      content: '{"dependencies":{}}'
    when: package_json.stat.exists == false
  - name: coc.nvim -> install extensions
    npm:
      name: "{{ item }}"
      path: ~/.config/coc/extensions
    with_items:
      - coc-css
      - coc-html
      - coc-json
      - coc-python
      - coc-tsserver
      - coc-yaml

- name: emmet-vim
  git:
    repo: https://github.com/mattn/emmet-vim.git
    dest: ~/.vim/bundle/emmet-vim

- block:
  - name: NERDTree -> git clone
    git:
      repo: https://github.com/preservim/nerdtree.git
      dest: ~/.vim/pack/vendor/start/nerdtree
  - name: NERDTree -> initiate
    shell: vim -u NONE -c "helptags ~/.vim/pack/vendor/start/nerdtree/doc" -c q
    changed_when: false

- block:
  - name: vim-go -> git clone
    git:
      repo: https://github.com/fatih/vim-go.git
      dest: ~/.vim/pack/plugins/start/vim-go
  - name: vim-go -> initiate
    shell: vim -esN +GoInstallBinaries +q
    changed_when: false

- name: "vim: VimCompletesMe"
  git:
    repo: git://github.com/ajh17/VimCompletesMe.git
    dest: ~/.vim/pack/vendor/start/VimCompletesMe

- name: source ~/.vimrc
  shell: vim -c "source ~/.vimrc" -c qa
  changed_when: false
