- name: vim -> install vim
  become: true
  package:
    name: vim
    state: latest

- name: vim -> install gvim
  become: true
  package:
    name: gvim
    state: latest

- name: vim directories -> create backup, swap, undo folders inside ~/.vim
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - ~/.vim/backup
    - ~/.vim/undo
    - ~/.vim/swap

- name: vim -> append config file
  include_tasks: "{{ task_reusable_dir }}/append-config.yml"
  vars:
    content_vimrc: |
      set backupdir=~/.vim/backup//
      set directory=~/.vim/swap//
      set undodir=~/.vim/undo//
    content_zshrc: |
      export EDITOR=vim
  with_items:
    - { name: "config: directories",
        line_comment_char: "\"",
        path: "{{ ansible_env.HOME }}/.vimrc",
        content: "{{ content_vimrc }}"}
    - { name: "config: directories",
        line_comment_char: "#",
        path: "{{ ansible_env.HOME }}/.zshrc",
        content: "{{ content_zshrc }}"}

# - name: source ~/.vimrc
#   shell: vim -c "source ~/.vimrc" -c qa
#   changed_when: false
