- name: serverless framework -> install globally
  npm:
    name: serverless
    global: yes

- name: serverless -> append config file
  include_tasks: "{{ task_reusable_dir }}/append-config.yml"
  vars:
    content: |
      export PATH="$HOME/.serverless/bin:$PATH"
  with_items:
    - { name: "serverless framework",
        path: "{{ ansible_env.HOME }}/.zshenv",
        content: "{{ content }}"}
