- name: ruby -> install
  become: true
  package:
    name: ruby
    state: latest

- name: ruby -> append config file
  include_tasks: "{{ task_reusable_dir }}/append-config.yml"
  vars:
    content: |
      if which ruby >/dev/null && which gem >/dev/null; then
          PATH="$(ruby -r rubygems -e 'puts Gem.user_dir')/bin:$PATH"
      fi
  with_items:
    - { name: "ruby",
        path: "{{ ansible_env.HOME }}/.zshenv",
        content: "{{ content }}"}
