- name: coc.nvim -> ensure folder exists for upcoming archive
  file:
    path: ~/.vim/pack/coc/start
    state: directory

- name: coc.nvim -> check if archive file exist
  stat:
    path: ~/.vim/pack/coc/start/coc-nvim-archive
  register: coc_nvim_archive

- name: coc.nvim -> download archive to this folder
  get_url:
    url: https://github.com/neoclide/coc.nvim/archive/release.tar.gz
    dest: ~/.vim/pack/coc/start/coc-nvim-archive

- name: coc.nvim -> extract archive
  unarchive:
    src: ~/.vim/pack/coc/start/coc-nvim-archive
    dest: ~/.vim/pack/coc/start/
  when: coc_nvim_archive.stat.exists == false

- name: coc.nvim -> create ~/.config/coc/extensions/ if not exist
  file:
    path: ~/.config/coc/extensions
    state: directory

- name: coc.nvim -> check if ~/.config/coc/extensions/package.json exist
  stat:
    path: ~/.config/coc/extensions/package.json
  register: package_json

- name: coc.nvim -> copy content to package.json
  copy:
    dest: ~/.config/coc/extensions/package.json
    content: '{"dependencies":{}}'
  when: package_json.stat.exists == false

- name: coc.nvim -> install extensions
  npm:
    name: "{{ item }}"
    path: ~/.config/coc/extensions
  with_items:
    - coc-css
    - coc-html
    - coc-json
    - coc-python
    - coc-tsserver
    - coc-yaml
