---
- hosts: "{{ hosts }}"
  vars:
    dotfiles_dir: "{{ ansible_env.HOME }}/Git/dotfiles"
    task_reusable_dir: "../task-reusable"
  tasks:
  - name: dotfiles -> git clone
    include_tasks: "{{ task_reusable_dir }}/git-clone.yml"
    with_items:
      - { dest_dir: "{{ ansible_env.HOME }}/Git/dotfiles",
          http: "https://github.com/tkiatd/dotfiles.git",
          ssh: "git@github.com:tkiatd/dotfiles.git" }
  - name: dotfiles -> make symlinks to dotfiles
    vars:
    file:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      state: link
    loop:
      - { src: "{{ dotfiles_dir }}/.ssh/config", dest: "{{ ansible_env.HOME }}/.ssh/config"}
      - { src: "{{ dotfiles_dir }}/.tmux.conf", dest: "{{ ansible_env.HOME }}/.tmux.conf"}
      - { src: "{{ dotfiles_dir }}/.vimrc", dest: "{{ ansible_env.HOME }}/.vimrc"}
      - { src: "{{ dotfiles_dir }}/.vim/colors", dest: "{{ ansible_env.HOME }}/.vim/colors"}
      - { src: "{{ dotfiles_dir }}/.vim/template", dest: "{{ ansible_env.HOME }}/.vim/template"}
      - { src: "{{ dotfiles_dir }}/.xpdfrc", dest: "{{ ansible_env.HOME }}/.xpdfrc"}
      - { src: "{{ dotfiles_dir }}/.zprofile", dest: "{{ ansible_env.HOME }}/.zprofile"}
      - { src: "{{ dotfiles_dir }}/.zshenv", dest: "{{ ansible_env.HOME }}/.zshenv"}
      - { src: "{{ dotfiles_dir }}/.zshrc", dest: "{{ ansible_env.HOME }}/.zshrc"}
