- name: git clone -> ensure {{ item.dest_dir | dirname }} exists
  file:
    path: "{{ item.dest_dir | dirname }}"
    state: directory

- name: git clone -> check if {{ item.dest_dir }} exists
  stat:
    path: "{{ item.dest_dir }}"
  register: item_dir

- name: git clone -> attempt ssh request
  git:
    repo: "{{ item.ssh }}"
    dest: "{{ item.dest_dir }}"
  ignore_errors: yes
  register: ssh_result
  when: item_dir.stat.exists == false

- name: git clone -> attempt http request (fallback)
  git:
    repo: "{{ item.http }}"
    dest: "{{ item.dest_dir }}"
  when: item_dir.stat.exists == false and ssh_result.failed == true
