- name: alsa -> install alsa-util
  become: true
  package:
    name: alsa-utils
    state: latest

- name: alsa -> run alsa as a service
  become: true
  file:
    src: /etc/sv/alsa
    dest: /var/service/alsa
    state: link
  when: ansible_os_family == "void"

- name: alsa -> create and copy content to ~/.asoundrc if not exist
  copy:
    src: "{{ git_dir }}/dotfiles/.asoundrc"
    dest: "{{ ansible_env.HOME }}"
    force: no
  when: ansible_os_family == "void"

- name: alsa -> append config file to /etc/asound.conf
  include_role:
    name: shared
    tasks_from: append-config
  vars:
    ansible_become: true
    content: |
      pcm.dsp {
          type plug
          slave.pcm "dmix"
      }
  with_items:
    - { name: "from ansible",
        line_comment_char: "#",
        path: "/etc/asound.conf",
        content: "{{ content }}"}
  when: ansible_os_family == "void"
