- name: fzf -> install
  become: true
  package:
    name: fzf
    state: latest

- name: fzf -> append config file
  include_tasks: "{{ task_reusable_dir }}/append-config.yml"
  vars:
    content: |
      source /usr/share/doc/fzf/completion.zsh # e.g. cd **<tab>
      export FZF_DEFAULT_COMMAND="ag --depth 4 --hidden --ignore .git -f -g \"\""
      export FZF_DEFAULT_OPTS="--layout=reverse --exact"
  with_items:
    - { name: "fzf",
        line_comment_char: "#",
        path: "{{ ansible_env.HOME }}/.zshenv",
        content: "{{ content }}"}
