- name: vim-pathogen -> ensure folders ~/.vim/bundle and ~/.vim/autoload exist
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - ~/.vim/bundle
    - ~/.vim/autoload

- name: vim-pathogen -> download
  get_url:
    url: https://tpo.pe/pathogen.vim
    dest: ~/.vim/autoload/pathogen.vim

- name: vim-pathogen -> append config file
  include_tasks: "{{ task_reusable_dir }}/append-config.yml"
  vars:
    content: |
      call pathogen#infect()
  with_items:
    - { name: "pkg manager: vim-pathogen",
        line_comment_char: "\"",
        path: "{{ ansible_env.HOME }}/.vimrc",
        content: "{{ content }}"}
