- name: dmenu -> git clone
  include_role:
    name: shared
    tasks_from: git-clone
  with_items:
    - { dest_dir: "{{ git_dir }}/suckless-dmenu",
        http: "https://gitlab.com/tkiatd/suckless-dmenu.git",
        ssh: "git@gitlab.com:tkiatd/suckless-dmenu.git" }
