- name: dmenu -> git clone
  include_role:
    name: shared
    tasks_from: git-clone
  with_items:
    - { dest_dir: "{{ git_dir }}/forked-dmenu",
        http: "https://gitlab.com/tkiatd/forked-dmenu.git",
        ssh: "git@gitlab.com:tkiatd/forked-dmenu.git" }
