- name: dmenu -> git clone
  include_role:
    name: shared
    tasks_from: git-clone
  with_items:
    - { dest_dir: "{{ git_dir }}/suckless-dmenu",
        http: "https://gitlab.com/tkiatd/suckless-dmenu.git",
        ssh: "git@gitlab.com:tkiatd/suckless-dmenu.git",
        branch: "my-config"}

- name: dmenu -> compile (freebsd)
  become: yes
  command: gmake install clean
  args:
    chdir: "{{ git_dir }}/suckless-dmenu"
  when: ansible_os_family == "FreeBSD"

- name: dmenu -> compile (linux)
  become: yes
  make:
    chdir: "{{ git_dir }}/suckless-dmenu"
    target: install
  when: ansible_os_family != "FreeBSD"
