- name: dwm -> git clone
  include_role:
    name: shared
    tasks_from: git-clone
  with_items:
    - { dest_dir: "{{ git_dir }}/forked-dwm",
        http: "https://gitlab.com/tkiatd/forked-dwm.git",
        ssh: "git@gitlab.com:tkiatd/forked-dwm.git" }
