- name: st -> git clone
  include_role:
    name: shared
    tasks_from: git-clone
  with_items:
    - { dest_dir: "{{ git_dir }}/suckless-st",
        http: "https://gitlab.com/tkiatd/suckless-st.git",
        ssh: "git@gitlab.com:tkiatd/suckless-st.git" }
