- name: xorg -> install
  become: true
  package:
    name: xorg
    state: latest

- name: xorg -> install related libraries
  become: true
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - libXft-devel
    - libX11-devel
    - libXinerama-devel
