- name: xorg -> install
  become: true
  package:
    name: xorg
    state: latest

- name: xorg -> copy config to ~/.xinitrc
  copy:
    src: "{{ dotfiles_dir }}/.xinitrc"
    dest: "{{ ansible_env.HOME }}"
