---
- name: install prerequisites
  become: yes
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - curl
    - gcc
    - python3

- name: install prerequisites (freebsd)
  become: yes
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - coreutils
    - gmake
    - gtar
    - make++
    - node
    - npm
    - the_silver_searcher
  when: ansible_os_family == "FreeBSD"

- name: install prerequisites (linux)
  become: yes
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - make
  when: ansible_os_family != "FreeBSD"

- include_tasks: nodejs-nvm.yml
  when: ansible_os_family != "FreeBSD"

- name: install utilities
  become: yes
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - gpgme
    - mc
    - redshift
    - tmux
    - tree
    - unzip
    - wget
    - yarn

- name: install utilities (freebsd)
  become: yes
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - gpart
  when: ansible_os_family == "FreeBSD"

- name: install utilities (linux)
  become: yes
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - gparted
    - tldr
    - xz
  when: ansible_os_family != "FreeBSD"
