---
- name: install git
  become: yes
  package:
    name: git
    state: latest

- name: tkiatd/dotfiles -> git clone
  include_role:
    name: shared
    tasks_from: git-clone
  with_items:
    - { dest_dir: "{{ dotfiles_dir }}",
        http: "https://github.com/tkiatd/dotfiles.git",
        ssh: "git@github.com:tkiatd/dotfiles.git" }

- name: install prerequisites
  become: yes
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - curl
    - gcc
    - python3

- name: install prerequisites (freebsd)
  become: yes
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - gmake
    - make++
    - node
  when: ansible_os_family == "FreeBSD"

- name: install prerequisites (linux)
  become: yes
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - make
  when: ansible_os_family != "FreeBSD"

- include_tasks: nodejs-nvm.yml
  when: ansible_os_family != "FreeBSD"

- name: install utilities
  become: yes
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - gpgme
    - mc
    - redshift
    - tmux
    - tree
    - unzip
    - wget
    - yarn

- name: install utilities (freebsd)
  become: yes
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - gpart
  when: ansible_os_family == "FreeBSD"

- name: install utilities (linux)
  become: yes
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - gparted
    - tldr
    - xz
  when: ansible_os_family != "FreeBSD"

      # 'xclip'
    #- go
    #- ruby
    #- vim
    
      #- name: install zsh
          #- name: copy .zshrc
          #  copy:
          #    src: "{{ dotfiles_dir }}/.zshrc"
          #    dest: "{{ ansible_env.HOME }}"

