- name: nvm -> install
  shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
  args:
    creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"

- name: nvm -> append config file
  include_role:
    name: shared
    tasks_from: append-config
  vars:
    content: |
      export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
  with_items:
    - { name: "nvm",
        line_comment_char: "#",
        path: "{{ ansible_env.HOME }}/.zshenv",
        content: "{{ content }}"}

- name: nodejs -> install node lts from nvm
  shell: . {{ ansible_env.HOME }}/.zshenv && nvm install --lts
  args:
    executable: /bin/zsh
  register: result
  changed_when: not result.stderr is search("already installed")

- name: nodejs -> create .nvmrc
  include_role:
    name: shared
    tasks_from: append-config
  vars:
    content: |
      lts/*
  with_items:
    - { name: "from ansible",
        line_comment_char: "#",
        path: "{{ ansible_env.HOME }}/.nvmrc",
        content: "{{ content }}"}

- name: nodejs -> source nvm
  shell: . {{ ansible_env.HOME }}/.nvm/nvm.sh
  changed_when: false

