all:
  children:
    cloud:
      hosts:
        ec2:
          ansible_connection: ssh
          ansible_ssh_host: ec2-13-251-165-144.ap-southeast-1.compute.amazonaws.com
          ansible_ssh_user: ec2-user
          ansible_ssh_private_key_file: ~/.ssh/tkiatd-AWS-key.pem
    local:
      hosts:
        localhost:
          ansible_connection: local
    remote:
      hosts:
