---
- name: execute playbook
  hosts: localhost
  remote_user: tkiatd
  vars:
    git_dir: "/mnt/Shared/Git"
  roles:
    - git
    - shell
    - prerequisites
    - language
    - display
    - audio
    - office

    # - internet
