---
- name: execute playbook.yml
  hosts: localhost
  remote_user: tkiatd
  vars:
    dotfiles_dir: "/mnt/Shared/Git/dotfiles"
    git_dir: "/mnt/Shared/Git"
  roles:
    - display
#     - prerequisites
#     - shell
#     - display
#     - internet
#     - office
