- name: vim install
  package:
    name: vim
    state: latest

- name: vim install -> create ~/.vimrc
  copy:
    dest: ~/.vimrc
    content: |
      " general
      hi SpecialKey ctermfg=67
      inoremap " ""<Esc>i
      inoremap ' ''<Esc>i
      inoremap ( ()<Esc>i
      inoremap [ []<Esc>i
      inoremap { {}<Esc>i
      inoremap (<CR> (<CR>)<Esc>ko<tab>
      inoremap [<CR> [<CR>]<Esc>ko<tab>
      inoremap {<CR> {<CR>}<Esc>ko<tab>
      set autoindent
      set list
      set listchars=tab:\|·,trail:_,eol:$
      set number
      set shiftwidth=2
      set tabstop=2
      set visualbell
      " plugin - NERDTree
      autocmd VimEnter * NERDTree
      let NERDTreeShowHidden=1
      " plugin - grubbox
      colorscheme gruvbox
      set background=dark

- name: vim install -> plugin_manager pathogen install -> create ~/.vim/autoload
  file:
    path: ~/.vim/autoload
    state: directory

- name: vim install -> plugin_manager pathogen install -> create ~/.vim/bundle
  file:
    path: ~/.vim/bundle
    state: directory
- name: vim install -> plugin_manager pathogen install -> download source
  shell: curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim
  args:
    warn: false
#- name: vim_pathogen-check
#  shell: "cat ~/.vimrc | grep pathogen#infect\\(\\) | wc -l"
#    register: pathogen_present
- name: vim install -> plugin_manager pathogen install -> add pathogen to .vimrc
  lineinfile:
    path: ~/.vimrc
    insertbefore: BOF
    line: "execute pathogen#infect()"
# when: pathogen_present.stdout == "0"
#
- name: vim install -> plugin emmet-vim initiate
  git:
    repo: https://github.com/mattn/emmet-vim.git
    dest: ~/.vim/bundle/emmet-vim

- name: vim install -> plugin NERDTree install
  git:
    repo: https://github.com/preservim/nerdtree.git
    dest: ~/.vim/pack/vendor/start/nerdtree
- name: vim install -> plugin NERDTree initiate
  shell: vim -u NONE -c "helptags ~/.vim/pack/vendor/start/nerdtree/doc" -c q

- name: vim install -> plugin vim-go install
  git:
    repo: https://github.com/fatih/vim-go.git
    dest: ~/.vim/pack/plugins/start/vim-go
- name: vim install -> plugin vim-go initiate
  shell: vim -E -s -c "GoInstallBinaries" -c qa

- name: vim install -> plugin VimCompletesMe install
  git:
    repo: git://github.com/ajh17/VimCompletesMe.git
    dest: ~/.vim/pack/vendor/start/VimCompletesMe

- name: vim install -> plugin gruvbox install
  git:
    repo: https://github.com/morhetz/gruvbox.git
    dest: ~/.vim/pack/default/start/gruvbox

- name: vim install -> source ~/.vimrc
  shell: vim -c "source ~/.vimrc" -c qa
