- name: golang -> install
  become: true
  package:
    name: go
    state: latest

- name: golang -> append config file
  include_role:
    name: shared
    tasks_from: append-config
  vars:
    content: |
      export GOPATH=$HOME/go
      export GOBIN=$GOPATH/bin
      export PATH=$PATH:$GOBIN
  with_items:
    - { name: "golang",
        line_comment_char: "#",
        path: "{{ ansible_env.HOME }}/.zshenv",
        content: "{{ content }}"}
