- name: essential programs installation
  become: true
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - curl
    - git
    - the_silver_searcher
    - tmux
    - wget
    - zsh
