- name: common programs installation (pkg manager)
  become: true
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - curl
    - git
    - the_silver_searcher
    - tmux
    - wget
    - zsh

- name: common programs installation (ruby gem)
  gem:
    name: asciidoctor
    state: latest
