- name: fzf -> install
  package:
    name: fzf
    state: latest

- name: fzf -> define config marker
  set_fact:
    marker_fzf: "fzf ===================================="

- name: fzf -> check if config exists in ~/.zprofile
  shell: "cat ~/.zprofile | grep '{{ marker_fzf }}' | wc -l"
  register: fzf_config
  changed_when: false

- name: fzf -> ensure config exists in ~/.zprofile
  blockinfile:
    path: ~/.zprofile
    marker: "# {mark}"
    marker_begin: "{{ marker_fzf }}"
    marker_end: "{{ marker_section_end }}"
    block: |
      export FZF_DEFAULT_COMMAND="ag --depth 4 --hidden --ignore .git -f -g \"\""
      export FZF_DEFAULT_OPTS="--layout=reverse"
  when: fzf_config.stdout == "0"
